# Generated by Django 3.1 on 2020-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
