# Generated by Django 3.1 on 2020-08-26 10:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200822_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
