# Generated by Django 3.1 on 2020-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20201001_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100, verbose_name='摘要'),
        ),
    ]
