# Generated by Django 3.1 on 2020-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/', verbose_name='文章标题图'),
        ),
    ]
