# Generated by Django 3.1 on 2020-10-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200919_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
