# Generated by Django 3.1 on 2020-10-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20201003_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='摘要'),
        ),
    ]
