# Generated by Django 3.1 on 2020-09-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='reviewer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='comment_body',
            field=models.TextField(),
        ),
    ]
