# Generated by Django 3.1 on 2020-09-07 22:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200907_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='comment_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
